FROM centos:7 as builder

RUN yum install -yq git python3 python3-pip wget mercurial which svn curl gcc && rm -rf /var/lib/apt/lists/*
RUN cd /opt && \
    git clone https://github.com/spack/spack -b v0.19.2 && \
    . /opt/spack/share/spack/setup-env.sh && \
    spack install miniconda3 && \
    spack clean -a
RUN echo -e "export PATH=$(. /opt/spack/share/spack/setup-env.sh && spack location -i miniconda3)/bin:${PATH}\n. /opt/spack/share/spack/setup-env.sh" > /etc/profile.d/ramble.sh
RUN cd /opt &&  \
    export PATH=$(. /opt/spack/share/spack/setup-env.sh && spack location -i miniconda3)/bin:${PATH} && \
    . spack/share/spack/setup-env.sh && \
    wget https://raw.githubusercontent.com/GoogleCloudPlatform/ramble/develop/requirements.txt && \
    conda install -qy pip && \
    python -m pip install -r /opt/requirements.txt

FROM centos:7

COPY --from=builder / /

ENTRYPOINT ["/bin/bash", "--rcfile", "/etc/profile", "-l", "-c", "$*", "--" ]
CMD [ "/bin/bash" ]
