ARG BASE_IMG=debian
ARG BASE_VER=12.5
FROM ${BASE_IMG}:${BASE_VER} AS builder

ARG SPACK_REF=releases/latest
ARG PYTHON_VER=3.11.14

RUN apt-get update && apt-get install -yq build-essential make git python3 python3-venv python3-pip wget mercurial which subversion curl gcc tar bzip2 && rm -rf /var/lib/apt/lists/*
RUN cd /opt && \
    git clone https://github.com/spack/spack && \
    cd spack && \
    git checkout $SPACK_REF && \
    . /opt/spack/share/spack/setup-env.sh && \
    spack install --deprecated py-pip ^python@${PYTHON_VER} && \
    spack clean -a
RUN echo ". /opt/spack/share/spack/setup-env.sh\n spack load py-pip ^python@${PYTHON_VER}\n export SPACK_PYTHON=`which python3`" > /etc/profile.d/ramble.sh
COPY requirements.txt requirements-dev.txt /opt/
RUN cd /opt &&  \
    . spack/share/spack/setup-env.sh && \
    spack load py-pip ^python@${PYTHON_VER} && \
    python -m pip install --no-cache-dir -r /opt/requirements-dev.txt
COPY share/ramble/cloud-build/container_test.sh /container_test.sh
RUN chmod a+x /container_test.sh
FROM ${BASE_IMG}:${BASE_VER}

COPY --from=builder / /

ENTRYPOINT ["/bin/bash", "--rcfile", "/etc/profile", "-l", "-c", "$*", "--" ]
CMD [ "/bin/bash" ]
