ARG BASE_IMG=centos
ARG BASE_VER=7
FROM ${BASE_IMG}:${BASE_VER} as builder

ARG SPACK_REF=releases/latest
ARG CONDA_VER=4.10.3
ARG PYTHON_VER=3.11.6
ARG PIP_VER=23.1.2
RUN yum install -yq git python3 python3-pip wget mercurial which svn curl gcc tar bzip2 gcc gcc-c++ gcc-gfortran tar xz gzip patch && rm -rf /var/lib/apt/lists/*
RUN echo "Will install py-pip ^python@$PYTHON_VER"
RUN cd /opt && \
    git clone https://github.com/spack/spack && \
    cd spack && \
    git checkout $SPACK_REF && \
    . /opt/spack/share/spack/setup-env.sh && \
    spack install py-pip@$PIP_VER ^python@$PYTHON_VER && \
    spack clean -a
RUN echo -e ". /opt/spack/share/spack/setup-env.sh\n spack load py-pip ^python@$PYTHON_VER\n export SPACK_PYTHON=`which python3`" > /etc/profile.d/ramble.sh
RUN cd /opt &&  \
    . spack/share/spack/setup-env.sh && \
    spack load py-pip ^python@$PYTHON_VER && \
    wget https://raw.githubusercontent.com/GoogleCloudPlatform/ramble/develop/requirements.txt && \
    python -m pip install -r /opt/requirements.txt

FROM ${BASE_IMG}:${BASE_VER}

COPY --from=builder / /

ENTRYPOINT ["/bin/bash", "--rcfile", "/etc/profile", "-l", "-c", "$*", "--" ]
CMD [ "/bin/bash" ]
