ARG BASE_IMG=debian
ARG BASE_VER=12.5
FROM ${BASE_IMG}:${BASE_VER} as builder

ARG SPACK_REF=releases/latest
ARG CONDA_VER=4.10.3
RUN apt-get update && apt-get install -yq git python3 python3-venv python3-pip wget mercurial which subversion curl gcc tar bzip2 && rm -rf /var/lib/apt/lists/*
RUN cd /opt && \
    git clone https://github.com/spack/spack && \
    cd spack && \
    git checkout $SPACK_REF && \
    . /opt/spack/share/spack/setup-env.sh && \
    spack install miniconda3@${CONDA_VER} && \
    spack clean -a
RUN echo -e "export PATH=$(. /opt/spack/share/spack/setup-env.sh && spack location -i miniconda3)/bin:${PATH}\n. /opt/spack/share/spack/setup-env.sh" > /etc/profile.d/ramble.sh
RUN cd /opt &&  \
    wget https://raw.githubusercontent.com/GoogleCloudPlatform/ramble/develop/requirements.txt && \
    python3 -m venv /opt/ramble_env && \
    . /opt/ramble_env/bin/activate && \
    . spack/share/spack/setup-env.sh && \
    pip3 install --upgrade pip && \
    pip3 install -r /opt/requirements.txt

FROM ${BASE_IMG}:${BASE_VER}

COPY --from=builder / /

ENTRYPOINT ["/bin/bash", "--rcfile", "/etc/profile", "-l", "-c", "$*", "--" ]
CMD [ "/bin/bash" ]
