ARG BASE_IMG=rockylinux
ARG BASE_VER=8
FROM ${BASE_IMG}:${BASE_VER} as builder

ARG SPACK_REF=releases/latest
ARG PYTHON_VER=3.11.14

RUN yum install -yq make git python3 python3-pip wget mercurial which svn curl gcc tar bzip2 gcc gcc-c++ gcc-gfortran tar xz gzip patch findutils && yum clean all && rm -rf /var/cache/yum
RUN cd /opt && \
    git clone https://github.com/spack/spack && \
    cd spack && \
    git checkout $SPACK_REF && \
    . /opt/spack/share/spack/setup-env.sh && \
    spack install --deprecated py-pip ^python@${PYTHON_VER} && \
    spack clean -a
RUN echo -e ". /opt/spack/share/spack/setup-env.sh\n spack load py-pip ^python@${PYTHON_VER}\n export SPACK_PYTHON=`which python3`" > /etc/profile.d/ramble.sh
COPY requirements.txt /opt/requirements.txt
COPY requirements-dev.txt /opt/requirements-dev.txt
COPY share/ramble/cloud-build/container_test.sh /container_test.sh
RUN cd /opt &&  \
    . spack/share/spack/setup-env.sh && \
    spack load py-pip ^python@${PYTHON_VER} && \
    chmod a+x /container_test.sh && \
    python -m pip install --no-cache-dir -r /opt/requirements-dev.txt
FROM ${BASE_IMG}:${BASE_VER}

COPY --from=builder / /

ENTRYPOINT ["/bin/bash", "--rcfile", "/etc/profile", "-l", "-c", "$*", "--" ]
CMD [ "/bin/bash" ]
