# Copyright 2022-2026 The Ramble Authors
#
# Licensed under the Apache License, Version 2.0 <LICENSE-APACHE or
# https://www.apache.org/licenses/LICENSE-2.0> or the MIT license
# <LICENSE-MIT or https://opensource.org/licenses/MIT>, at your
# option. This file may not be copied, modified, or distributed
# except according to those terms.

# This is similar to ramble-image-builder.yaml, but it only validates
# the Dockerfiles for PRs, without pushing images to the registry.

tags:
  # This is used for filtering builds related to a specific PR
  - '$TRIGGER_NAME-$_PR_NUMBER'
steps:
  # Cancel older builds
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'share/ramble/cloud-build/cancel-older-builds.sh'
    env:
      - 'PR_NUMBER=$_PR_NUMBER'
      - 'TRIGGER_NAME=$TRIGGER_NAME'
      - 'BUILD_ID=$BUILD_ID'
      - 'PROJECT_ID=$PROJECT_ID'
  - name: 'gcr.io/cloud-builders/docker'
    id: build-image
    args:
      - 'build'
      - '-f'
      - 'share/ramble/cloud-build/Dockerfile-${_PKG_MANAGER}'
      - '--build-arg'
      - 'SPACK_REF=${_SPACK_REF}'
      - '--build-arg'
      - 'PYTHON_VER=${_PYTHON_VER}'
      - '.'
    waitFor: ['-']

# For PR validation, only use one set of versions.
substitutions:
  _SPACK_REF: v1.1.1
  _PYTHON_VER: 3.11.14
  _PKG_MANAGER: apt

timeout: 3600s
queueTtl: 7200s
options:
  machineType: E2_HIGHCPU_8
