# Copyright 2022-2024 The Ramble Authors
#
# Licensed under the Apache License, Version 2.0 <LICENSE-APACHE or
# https://www.apache.org/licenses/LICENSE-2.0> or the MIT license
# <LICENSE-MIT or https://opensource.org/licenses/MIT>, at your
# option. This file may not be copied, modified, or distributed
# except according to those terms.


steps:
  - name: gcr.io/cloud-builders/git
    args:
      - fetch
      - '--unshallow'
    id: ramble-clone
  - name: us-central1-docker.pkg.dev/$PROJECT_ID/ramble-repo/ramble-${_BASE_IMG}-${_BASE_VER}-spack${_SPACK_REF}-conda${_CONDA_VER}:latest
    args:
      - '-c'
      - |
        cd /workspace

        git branch develop origin/develop

        export PATH=$$(. /opt/spack/share/spack/setup-env.sh && spack location -i miniconda3)/bin:$${PATH}

        . /opt/spack/share/spack/setup-env.sh
        . /workspace/share/ramble/setup-env.sh

        echo "Spack version is $(spack --version)"
        echo "Python version is $(python3 --version)"

        ramble style -U
        # $$ characters are required for cloud-build:
        # https://cloud.google.com/build/docs/configuring-builds/substitute-variable-values
        style_err=$$?

        ramble commands --update-completion
        git diff --exit-code &> /dev/null
        # $$ characters are required for cloud-build:
        # https://cloud.google.com/build/docs/configuring-builds/substitute-variable-values
        commands_err=$$?

        ramble license verify
        # $$ characters are required for cloud-build:
        # https://cloud.google.com/build/docs/configuring-builds/substitute-variable-values
        license_err=$$?

        # Test removing a dependency
        conda uninstall -qy pytest

        ramble help
        # $$ characters are required for cloud-build:
        # https://cloud.google.com/build/docs/configuring-builds/substitute-variable-values
        missing_req_err=$$?

        error=0
        if [ $$missing_req_err -gt 0 ]; then
          echo " ***** Ramble failed to work when requirements.txt were not installed"
          error=1
        fi

        # $$ characters are required for cloud-build:
        # https://cloud.google.com/build/docs/configuring-builds/substitute-variable-values
        if [ $$style_err -gt 0 ]; then
          echo "Style error = $$style_err"
          echo " ***** Style tests failed"
          error=1
        fi

        # $$ characters are required for cloud-build:
        # https://cloud.google.com/build/docs/configuring-builds/substitute-variable-values
        if [ $$commands_err -gt 0 ]; then
          echo "Commands error = $$commands_err"
          echo " ***** Commands changed and bash completion is not updated."
          echo "       Please use the following to fix this:"
          echo "         ramble commands --update-completion"
          error=1
        fi

        # $$ characters are required for cloud-build:
        # https://cloud.google.com/build/docs/configuring-builds/substitute-variable-values
        if [ $$license_err -gt 0 ]; then
          echo "License check error = $$license_err"
          echo " ***** License check failed"
          error=1
        fi

        # $$ characters are required for cloud-build:
        # https://cloud.google.com/build/docs/configuring-builds/substitute-variable-values
        exit $$error
    id: ramble-style-tests
    entrypoint: /bin/bash
substitutions:
  _SPACK_REF: v0.21.2
  _CONDA_VER: 22.11.1
  _BASE_IMG: centos
  _BASE_VER: '7'
timeout: 600s
options:
  machineType: N1_HIGHCPU_8
