# Copyright 2022-2026 The Ramble Authors
#
# Licensed under the Apache License, Version 2.0 <LICENSE-APACHE or
# https://www.apache.org/licenses/LICENSE-2.0> or the MIT license
# <LICENSE-MIT or https://opensource.org/licenses/MIT>, at your
# option. This file may not be copied, modified, or distributed
# except according to those terms.
# SPDX-License-Identifier: (Apache-2.0 OR MIT)
"""This package implements Ramble workspaces."""

from .workspace import (
    AUXILIARY_SOFTWARE_DIR_NAME,
    CONFIG_FILE_NAME,
    LICENSE_INC_NAME,
    LICENSES_FILE_NAME,
    METADATA_FILE_NAME,
    RAMBLE_WORKSPACE_VAR,
    TEMPLATE_EXTENSION,
    WORKSPACE_CONFIG_PATH,
    WORKSPACE_LOG_PATH,
    WORKSPACE_SHARED_PATH,
    WORKSPACE_SOFTWARE_PATH,
    RambleActiveWorkspaceError,
    RambleConflictingDefinitionError,
    RambleInvalidTemplateNameError,
    RambleMissingApplicationDirError,
    RambleMissingApplicationError,
    RambleMissingExperimentError,
    RambleMissingWorkloadError,
    RambleWorkspaceError,
    Workspace,
    activate,
    active,
    active_workspace,
    all_config_files,
    all_template_paths,
    all_workspace_names,
    config_dict,
    config_file,
    create,
    deactivate,
    exists,
    get_filepath,
    get_workspace_path,
    is_workspace_dir,
    licenses_file,
    namespace,
    no_active_workspace,
    read,
    root,
    template_path,
)

__all__ = [
    "Workspace",
    "TEMPLATE_EXTENSION",
    "LICENSE_INC_NAME",
    "RambleWorkspaceError",
    "RambleConflictingDefinitionError",
    "RambleActiveWorkspaceError",
    "RambleMissingApplicationError",
    "RambleMissingWorkloadError",
    "RambleMissingExperimentError",
    "RambleMissingApplicationDirError",
    "RambleInvalidTemplateNameError",
    "activate",
    "active",
    "active_workspace",
    "all_workspace_names",
    "config_dict",
    "create",
    "deactivate",
    "exists",
    "is_workspace_dir",
    "get_workspace_path",
    "get_filepath",
    "config_file",
    "CONFIG_FILE_NAME",
    "all_config_files",
    "licenses_file",
    "LICENSES_FILE_NAME",
    "METADATA_FILE_NAME",
    "WORKSPACE_SOFTWARE_PATH",
    "AUXILIARY_SOFTWARE_DIR_NAME",
    "template_path",
    "all_template_paths",
    "no_active_workspace",
    "read",
    "root",
    "RAMBLE_WORKSPACE_VAR",
    "namespace",
    "WORKSPACE_CONFIG_PATH",
    "WORKSPACE_LOG_PATH",
    "WORKSPACE_SHARED_PATH",
]
