repos:
- repo: local
  hooks:
  - id: flake8
    name: flake8
    entry: share/ramble/qa/run-flake8-tests
    language: system
  - id: short-unit-tests
    name: short-unit-tests
    entry: share/ramble/qa/run-unit-tests
    language: system
    stages: [push]
