repos:
- repo: local
  hooks:
  - id: style
    name: style
    entry: share/ramble/qa/run-style-tests
    language: system
  - id: short-unit-tests
    name: short-unit-tests
    entry: share/ramble/qa/run-unit-tests
    language: system
    stages: [push]
