version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.12"

sphinx:
  configuration: lib/ramble/docs/conf.py
  fail_on_warning: true

python:
  install:
    - requirements: lib/ramble/docs/requirements.txt
