[files]
extend-exclude = [
    ".git/",
    # Copy of https://github.com/spack/spack/tree/develop/lib/spack
    "lib/ramble/external/",
    "lib/ramble/llnl/",
    "lib/ramble/spack/",
    "var/",
]
ignore-hidden = false

[default]
extend-ignore-re = [
    "\\bFOMs",
]

[default.extend-words]
"fom" = "fom"
"namd" = "namd"

[default.extend-identifiers]
"ATPase" = "ATPase"
"cachable" = "cachable"
"clen" = "clen"
