[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ramble"
version = "0.6.0"
description = "A multi-platform experimentation framework written in python."
readme = "README.md"
requires-python = ">=3.6"
license = "Apache-2.0 OR MIT"
license-files = ["LICENSE-APACHE", "LICENSE-MIT"]
classifiers = [
    "Programming Language :: Python :: 3",
]
dynamic = ["dependencies"]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}

[tool.setuptools]
package-dir = { "" = "." }
include-package-data = true

[tool.setuptools.packages.find]
where = ["."]
include = ["lib*", "etc*", "var*", "bin*", "share*"]
namespaces = true

[tool.setuptools.package-data]
"*" = ["*"]

[tool.black]
line-length = 99
# Older versions of black (like the ones compatible with py3.7)
# don't recognize newer python versions like py312.
target-version = ["py36", "py37", "py38", "py39", "py310"]
include = '''
    \.pyi?$
'''
force-exclude = '''
/(
    \.git
  | etc
  | share
  | var
  | lib/ramble/external
  | lib/ramble/spack
  | lib/ramble/llnl
  | __pycache__
)/
'''

[tool.isort]
profile = "black"
line_length = 99
filter_files = true
skip_glob = [
  "**/lib/ramble/external/**",
  "**/lib/ramble/llnl/**",
  "**/lib/ramble/spack/**",
]
sections = [
  "FUTURE",
  "STDLIB",
  "THIRDPARTY",
  "LLNL",
  "FIRSTPARTY",
  "SPACK",
  "LOCALFOLDER",
]
known_first_party = "ramble"
known_spack = "spack"
known_llnl = "llnl"
known_third_party = ["ruamel", "jsonschema"]

[tool.coverage.run]
parallel = true
# subprocess assumes parallel=true
# This patch allows coverage.py to accurately capture
# subprocess calls.
patch = ["subprocess"]
data_file = "./tests-coverage/.coverage"
include = [
  "**/bin/ramble",
  "**/bin/ramble-python",
  "**/lib/ramble/ramble/**",
  "**/lib/ramble/ramble/schema/**",
  "**/lib/ramble/ramble/cmd/**",
  "**/var/ramble/repos/builtin/base_classes/**",
]
omit = [
    "**/spack/lib/**",
    "**/spack/var/**",
    "lib/ramble/spack/**",
    "lib/ramble/external/**",
    "lib/ramble/llnl/**",
    "share/**",
    # Perf tests don't run in the coverage CI build, so exclude them here.
    # They do run in a separate CI build though.
    "**/lib/ramble/ramble/test/end_to_end/perf_tests/**",
]

[tool.coverage.report]
# Regexes for lines to exclude from consideration
exclude_lines = [
    # Have to re-enable the standard pragma
    'pragma: no cover',

    # Don't complain about missing debug-only code:
    'def __repr__',
    'if self\.debug',

    # Don't complain if tests don't hit defensive assertion code:
    'raise AssertionError',
    'raise NotImplementedError',

    # Don't complain if non-runnable code isn't run:
    'if 0:',
    'if False:',
    'if __name__ == .__main__.:',
]
ignore_errors = true
include = [
  "**/bin/ramble",
  "**/bin/ramble-python",
  "**/lib/ramble/ramble/**",
  "**/lib/ramble/ramble/schema/**",
  "**/lib/ramble/ramble/cmd/**",
]
omit = [
    "**/spack/lib/**",
    "**/spack/var/**",
    "lib/ramble/spack/**",
    "lib/ramble/external/**",
    "lib/ramble/llnl/**",
    "share/**",
]

[tool.coverage.html]
directory = "htmlcov"

[tool.mypy]
# Use a common version (3.10 is the lowest supported version)
# Otherwise mypy uses the running python's version
python_version = "3.10"
no_site_packages = true
# TODO: Add in more files for type-checking
# For now, only type-check the util directory
files = [
  "lib/ramble/ramble/**/*.py",
  "share/ramble/scripts/**/*.py",
]
ignore_errors = true
ignore_missing_imports = true
allow_redefinition = true

[[tool.mypy.overrides]]
# Only enable ramble modules and share helper scripts
module = [
    "ramble.*",
    "_ramble_cleaner",
    "_ramble_file_editor",
]
ignore_errors = false

[[tool.mypy.overrides]]
# Ignore numpy type stubs since they use 3.12 syntax
module = "numpy.*"
follow_imports = "skip"

[[tool.mypy.overrides]]
# TODO: Add more modules here for exhaustive type-checking
module = [
    "ramble.util.*",
    "ramble.error",
    "ramble.paths",
    "ramble.filters",
    "_ramble_cleaner",
    "_ramble_file_editor",
]
check_untyped_defs = true

[tool.ruff]
extend-include = ["bin/ramble"]
extend-exclude = [
  "lib/ramble/external",
  "lib/ramble/spack",
  "lib/ramble/llnl",
]

[tool.ruff.lint]
preview = true
# B905 requires Python 3.9 or up.
ignore = ["B905", "PERF203"]
select = [
    "E4", "E7", "E9", "F", "B", "C4",
    # Enable some useful preview rules
    "B043",   # del-attr-with-constant
    "PLW1510",# subprocess-run-without-check
    "PLW1514",# unspecified-encoding
    "PIE",    # flake8-pie
    "PT014",  # pytest-duplicate-parametrize-test-cases
    "T10",    # flake8-debugger
    "RUF019", # unnecessary-key-check
    "PLC0206",# dict-index-missing-items
    "SIM118", # in-dict-keys
    "PERF",
    "RUF015", # unnecessary-iterable-allocation
    "FURB192",# sorted-min-max
    "FURB118",# reimplemented-operator
    "TID",    # flake8-tidy-imports
]

[tool.ruff.lint.flake8-tidy-imports.banned-api]
# Even though `py` is neither vendored nor listed in the deps, `pytest` has a dependency
# on it. Use linter to ban its usage.
"py" = { msg = "The legacy `py` library is deprecated and should not be used." }
# These are used to enforce the gradual moving away from vendored Spack dependencies
"spack.util.naming" = { msg = "Core Ramble code should not rely on spack.util.naming." }
"spack.util.cpus" = { msg = "Core Ramble code should not rely on spack.util.cpus." }
"spack.util.spack_json" = { msg = "Core Ramble code should not rely on spack.util.spack_json." }

[tool.ruff.lint.per-file-ignores]
"lib/ramble/ramble/*kit.py" = ["F403"]
"var/ramble/repos/**/*.py" = ["F403", "F405"]
