ramble:
  variants:
    package_manager: spack
    workflow_manager: slurm
  # defined in includes/application.yaml
  applications: {}
  # defined in includes/software.yaml
  software:
    packages: {}
    environments: {}
