#!/bin/sh
# Copyright 2022-2024 The Ramble Authors
#
# Licensed under the Apache License, Version 2.0 <LICENSE-APACHE or
# https://www.apache.org/licenses/LICENSE-2.0> or the MIT license
# <LICENSE-MIT or https://opensource.org/licenses/MIT>, at your
# option. This file may not be copied, modified, or distributed
# except according to those terms.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

#
# Description:
#     Runs source code style checks on RAmble.
#     See $RAMBLE_ROOT/.flake8 for a list of
#     approved exceptions.
#
# Usage:
#     run-flake8-tests
#
ERROR=0
. "$(dirname $0)/setup.sh"
check_dependencies flake8
if [ $? != 0 ]; then
  ERROR=1
fi


# verify that the code style is correct
ramble flake8 -U
if [ $? != 0 ]; then
  ERROR=1
fi

# verify that the license headers are present
ramble license verify
if [ $? != 0 ]; then
  ERROR=1
fi

if [ $ERROR == 1 ]; then
    exit 1
fi
