#!/bin/bash -e
# Copyright 2022-2026 The Ramble Authors
#
# Licensed under the Apache License, Version 2.0 <LICENSE-APACHE or
# https://www.apache.org/licenses/LICENSE-2.0> or the MIT license
# <LICENSE-MIT or https://opensource.org/licenses/MIT>, at your
# option. This file may not be copied, modified, or distributed
# except according to those terms.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

#
# Description:
#     Runs Ramble unit tests.
#
# Usage:
#     run-unit-tests [test ...]
#
# Options:
#     Optionally add one or more unit tests
#     to only run these tests.
#

#-----------------------------------------------------------
# Run a few initial commands and set up test environment
#-----------------------------------------------------------
ORIGINAL_PATH="$PATH"
ERROR=0

. "$(dirname $0)/setup.sh"
check_dependencies $coverage git hg svn
if [ $? != 0 ]; then
    ERROR=1
fi

# Move to root directory of Ramble
# Allows script to be run from anywhere
cd "$RAMBLE_ROOT"

# Run ramble help to cover command import
bin/ramble -h
if [ $? != 0 ]; then
    ERROR=1
fi
bin/ramble help -a
if [ $? != 0 ]; then
    ERROR=1
fi

export UNIT_TEST_COVERAGE_PREFIX=""
if [[ "$UNIT_TEST_COVERAGE" == "true" ]]; then
  export UNIT_TEST_COVERAGE_PREFIX="coverage run --rcfile=pyproject.toml"
fi

export PYTEST_ADDOPTS=""

N_PROCS=${N_PROCS:-auto}
# Check if xdist is available
if python -m pytest -VV 2>&1 | grep xdist; then
  export PYTEST_ADDOPTS="$PYTEST_ADDOPTS -n $N_PROCS"
fi

#-----------------------------------------------------------
# Run unit tests with code coverage
#-----------------------------------------------------------

if [[ "$LONG" == "true" ]]; then
  echo "Running fast unit tests..."
  ${UNIT_TEST_COVERAGE_PREFIX} $(which ramble) unit-test ${PYTEST_ADDOPTS} -x --verbose --fast
  if [ $? != 0 ]; then
    ERROR=1
  else
    echo "Running slow unit tests..."
    ${UNIT_TEST_COVERAGE_PREFIX} $(which ramble) unit-test ${PYTEST_ADDOPTS} -x --verbose --slow
    if [ $? != 0 ]; then
      ERROR=1
    fi
  fi
else
  echo "Running fast unit tests..."
  ${UNIT_TEST_COVERAGE_PREFIX} $(which ramble) unit-test ${PYTEST_ADDOPTS} -x --verbose --fast
  if [ $? != 0 ]; then
    ERROR=1
  fi
fi

if [[ "$UNIT_TEST_COVERAGE" == "true" ]]; then
  coverage combine
fi

if [[ "$PUSH_CODECOV" ]]; then
  if [[ -z "$COMMIT_SHA" ]]; then
    export COMMIT_SHA=`git -C $(dirname $0) log -n 1 --format="%H"`
  fi

  DEFAULT_BASE_BRANCH="develop"
  TARGET_BRANCH=${BASE_BRANCH:-$DEFAULT_BASE_BRANCH}

  echo "Comparing against base branch: origin/$TARGET_BRANCH"

  # Calculate merge base between the PR commit and origin/$TARGET_BRANCH
  MERGE_BASE_SHA=$(git merge-base "$COMMIT_SHA" "origin/$TARGET_BRANCH" || echo "")
  
  echo "Processing codecov upload for commit $COMMIT_SHA"

  UPLOAD_ARGS="-C $COMMIT_SHA"
  if [[ -n "$PR_NUMBER" ]]; then
    UPLOAD_ARGS="$UPLOAD_ARGS --pr $PR_NUMBER"
  fi
  if [[ -n "$MERGE_BASE_SHA" ]]; then
    echo "Picking PR base: $MERGE_BASE_SHA"
    if [[ -n "$PR_NUMBER" ]]; then
      codecovcli pr-base-picking --base-sha $MERGE_BASE_SHA --pr $PR_NUMBER --slug "Ramble-Project/ramble"
    else
      echo "Skipping pr-base-picking: PR_NUMBER not set"
    fi
  fi
  codecovcli upload-process $UPLOAD_ARGS
fi

if [ $ERROR == 1 ]; then
    exit 1
fi
