name: "\U0001F38A Feature request" 
description: Suggest adding a feature that is not yet in Ramble
labels: [feature]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Please add a concise summary of your suggestion here.
    validations:
      required: true
  - type: textarea
    id: rationale
    attributes:
      label: Rationale
      description: Is your feature request related to a problem? Please describe it!
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the solution you'd like and the alternatives you have considered.
  - type: textarea
    id: additional_information
    attributes:
      label: Additional information
      description: Add any other context about the feature request here.
  - type: checkboxes
    id: checks
    attributes:
      label: General information
      options:
        - label: I have run `ramble --version` and reported the version of Ramble
          required: true
        - label: I have searched the issues of this repo and believe this is not a duplicate
          required: true
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to contribute to Ramble!
