ramble:
  variables:
    mpi_command: 'mpirun -n {n_ranks} -ppn {processes_per_node}'
    batch_submit: '{execute_experiment}'
    n_ranks: '{processes_per_node}*{n_nodes}'
  applications:
    openfoam:
      workloads:
        motorbike:
          experiments:
            test_{partition}_{processes_per_node}_{n_nodes}:
              variables:
                partition: ['part1', 'part2']
                processes_per_node: ['16', '32']
                #^-- (partition, processes_per_node) -> (part1, 16), (part2, 32)
                n_nodes: ['2', '4']
                wrf_path: execute_experiment in wrfv4.CONUS_2p5km.new_test
              matrices:
                - - n_nodes
                #^-- (partition, processes_per_node, n_nodes) ->
                                #(part1, 16, 2), (part1, 16, 4)
                                #(part2, 32, 2), (part2, 32, 4)
    wrfv4:
      workloads:
        CONUS_2p5km:
          experiments:
            new_test:
              variables:
                n_ranks: '1'
                n_nodes: '1'
  spack:
    packages:
      gcc9:
        spack_spec: gcc@9.3.0 target=x86_64
        compiler_spec: gcc@9.3.0
      ompi412:
        spack_spec: openmpi@4.1.2 +legacylaunchers +pmi +thread_multiple +cxx target=x86_64
        compiler: gcc9
      impi2021:
        spack_spec: intel-oneapi-mpi@2021.11.0
        compiler: gcc9
      openfoam:
        spack_spec: openfoam-org@7
        compiler: gcc9
      flex:
        spack_spec: flex@2.6.4
        compiler: gcc9
      wrfv4:
        spack_spec: wrf@4.2 build_type=dm+sm compile_type=em_real nesting=basic ~chem ~pnetcdf
        compiler: gcc9
    environments:
      openfoam:
        packages:
        - ompi412
        - flex
        - openfoam
      wrfv4:
        packages:
        - impi2021
        - wrfv4
