# Copyright 2022-2026 The Ramble Authors
# 
# Licensed under the Apache License, Version 2.0 <LICENSE-APACHE or
# https://www.apache.org/licenses/LICENSE-2.0> or the MIT license
# <LICENSE-MIT or https://opensource.org/licenses/MIT>, at your
# option. This file may not be copied, modified, or distributed
# except according to those terms.

ramble:
  variants:
    package_manager: spack
  variables:
    mpi_command: mpirun -n {n_ranks} -ppn {processes_per_node}
    batch_submit: '{execute_experiment}'
    n_ranks: '{processes_per_node}*{n_nodes}'
  applications:
    openfoam-org@10:
      workloads:
        motorbike:
          experiments:
            test_{partition}_{processes_per_node}_{n_nodes}:
              variables:
                partition: [part1, part2]
                processes_per_node: [16, 32]
                #^-- (partition, processes_per_node) -> (part1, 16), (part2, 32)
                n_nodes: [2, 4]
                wrf_path: execute_experiment in wrfv4.CONUS_2p5km.new_test
              matrices:
                - - n_nodes
                #^-- (partition, processes_per_node, n_nodes) ->
                                #(part1, 16, 2), (part1, 16, 4)
                                #(part2, 32, 2), (part2, 32, 4)
    wrf@4.2:
      workloads:
        CONUS_2p5km:
          experiments:
            new_test:
              variables:
                n_ranks: 1
                n_nodes: 1
  software:
    packages:
      gcc14:
        pkg_spec: gcc@14.2.0 target=x86_64
        compiler_spec: gcc@14.2.0
      ompi508:
        pkg_spec: openmpi@5.0.8 +legacylaunchers +pmi +thread_multiple +cxx target=x86_64
        compiler: gcc14
      intel-mpi:
        pkg_spec: intel-oneapi-mpi@2021.17.2
        compiler: gcc14
      openfoam-org-{application::openfoam-org::version}:
        pkg_spec: openfoam-org@{application::openfoam-org::version}
        compiler: gcc14
      flex:
        pkg_spec: flex@2.6.4
        compiler: gcc14
      wrfv4-{application::wrf::version}:
        pkg_spec: wrf@{application::wrf::version} build_type=dm+sm compile_type=em_real nesting=basic ~chem ~pnetcdf
        compiler: gcc14
    environments:
      openfoam-org@10:
        packages:
        - ompi508
        - flex
        - openfoam-org-{application::openfoam-org::version}
      wrf@4.2:
        packages:
        - intel-mpi
        - wrfv4-{application::wrf::version}
