# Copyright 2022-2026 The Ramble Authors
# 
# Licensed under the Apache License, Version 2.0 <LICENSE-APACHE or
# https://www.apache.org/licenses/LICENSE-2.0> or the MIT license
# <LICENSE-MIT or https://opensource.org/licenses/MIT>, at your
# option. This file may not be copied, modified, or distributed
# except according to those terms.

ramble:
  variants:
    package_manager: spack
  env_vars:
    set:
      I_MPI_DEBUG: 5
  variables:
    mpi_command: mpirun -n {n_ranks} -ppn {processes_per_node}
    batch_submit: '{execute_experiment}'
    processes_per_node: 16
    n_ranks: '{processes_per_node}*{n_nodes}'
  applications:
    openfoam-org@10:
      workloads:
        motorbike:
          experiments:
            test_{partition}_{processes_per_node}_{n_nodes}_{env_name}:
              env_vars:
                set:
                  OMP_NUM_THREADS: '{n_threads}'
              variables:
                partition: [part1, part2]
                processes_per_node: [16, 32]
                env_name: [openfoam-skx, openfoam-zen2]
                #^-- (partition, processes_per_node) -> (part1, 16, openfoam-skx), (part2, 32, openfoam-zen2)
                n_nodes: [2, 4]
              matrices:
                - matrix_a:
                  - n_nodes
                #^-- (partition, processes_per_node, n_nodes) ->
                                #(part1, 16, openfoam-skx, 2), (part1, 16, openfoam-skx, 4)
                                #(part2, 32, openfoam-zen2, 2), (part2, 32, openfoam-zen2, 4)
  software:
    packages:
      gcc14:
        pkg_spec: gcc@14.2.0 target=x86_64
        compiler_spec: gcc@14.2.0
      ompi508:
        pkg_spec: openmpi@5.0.8 +legacylaunchers +pmi +thread_multiple +cxx target=x86_64
        compiler: gcc14
      openfoam-skx:
        pkg_spec: openfoam-org@{application::openfoam-org::version} target=cascadelake
        compiler: gcc14
      openfoam-zen2:
        pkg_spec: openfoam-org@{application::openfoam-org::version} target=zen2
        compiler: gcc14
      flex:
        pkg_spec: flex@2.6.4
        compiler: gcc14
    environments:
      openfoam-skx:
        packages:
        - ompi508
        - openfoam-skx
        - flex
      openfoam-zen2:
        packages:
        - ompi508
        - openfoam-zen2
        - flex
