# Copyright 2022-2024 The Ramble Authors
# 
# Licensed under the Apache License, Version 2.0 <LICENSE-APACHE or
# https://www.apache.org/licenses/LICENSE-2.0> or the MIT license
# <LICENSE-MIT or https://opensource.org/licenses/MIT>, at your
# option. This file may not be copied, modified, or distributed
# except according to those terms.

ramble:
  variants:
    package_manager: eessi
  env_vars:
    set:
      OMP_NUM_THREADS: '{n_threads}'
      # Control which microarchitecture to use with EESSI
      EESSI_SOFTWARE_SUBDIR_OVERRIDE: '{eessi_arch_dir}'
  variables:
    processes_per_node: 16
    # OpenMPI flags
    mpi_command: mpirun -n {n_ranks} --map-by ppr:{processes_per_node}:node
    batch_submit: '{execute_experiment}'
    arch_name: [generic, haswell, skylake_avx512]
    eessi_arch_dir: [x86_64/generic, x86_64/intel/haswell, x86_64/intel/skylake_avx512]
  zips:
    arch_conf:
    - arch_name
    - eessi_arch_dir
  applications:
    gromacs: # Application name
      workloads:
        '{app_workloads}': # Workload name from application
          experiments:
            '{type}_{n_ranks}ranks-{arch_name}': # Arbitrary experiment name
              variables:
                app_workloads: [water_gmx50, water_bare]
                n_ranks: [1, 2]
                n_threads: 1
                size: '0003'
                type: [pme, rf]
                eessi_version: '2023.06'
              matrix:
              - app_workloads
              - type
              - n_ranks
              - arch_conf
  software:
    packages:
      gromacs:
        pkg_spec: GROMACS/2024.1-foss-2023b
    environments:
      gromacs:
        packages:
        - gromacs
