# Copyright 2022-2024 The Ramble Authors

# Licensed under the Apache License, Version 2.0 <LICENSE-APACHE or
# https://www.apache.org/licenses/LICENSE-2.0> or the MIT license
# <LICENSE-MIT or https://opensource.org/licenses/MIT>, at your
# option. This file may not be copied, modified, or distributed
# except according to those terms.

ramble:
  variants:
    package_manager: spack
  env_vars:
    set:
      OMP_NUM_THREADS: '{n_threads}'
  variables:
    n_ranks: '{processes_per_node}*{n_nodes}'
    platform: ['platform1', 'platform2']
    processes_per_node: ['16', '18']

    # Execution Template
    batch_submit: '{execute_experiment}'
    mpi_command: 'mpirun {{mpi_name}_args}'

    # Experiment Expansions
    mpi_name: ['intel-mpi', 'openmpi']
    intel-mpi_args: '-n {n_ranks} -ppn {processes_per_node}'
    openmpi_args: '--np {n_ranks} --map-by ppr:{processes_per_node}:node -x OMP_NUM_THREADS'
  zips:
    platform_config:
    - platform
    - processes_per_node
  applications:
    wrfv4:
      workloads:
        CONUS_12km:
          experiments:
            scaling_{n_nodes}_{platform}_{mpi_name}:
              variables:
                n_nodes: [1, 2]
                env_name: 'wrfv4-{mpi_name}'
              matrix:
              - platform_config
              - n_nodes
              - mpi_name
  software:
    packages:
      gcc9:
        pkg_spec: gcc@9.4.0
      intel-mpi:
        pkg_spec: intel-oneapi-mpi@2021.11.0
        compiler: gcc9
      openmpi:
        pkg_spec: openmpi@3.1.6 +orterunprefix
      wrfv4:
        pkg_spec: wrf@4.2 build_type=dm+sm compile_type=em_real nesting=basic ~chem
          ~pnetcdf
        compiler: gcc9
    environments:
      wrfv4-{mpi_name}:
        packages:
        - '{mpi_name}'
        - wrfv4
