# Copyright 2022-2026 The Ramble Authors

# Licensed under the Apache License, Version 2.0 <LICENSE-APACHE or
# https://www.apache.org/licenses/LICENSE-2.0> or the MIT license
# <LICENSE-MIT or https://opensource.org/licenses/MIT>, at your
# option. This file may not be copied, modified, or distributed
# except according to those terms.

ramble:
  variants:
    package_manager: spack
  env_vars:
    set:
      OMP_NUM_THREADS: '{n_threads}'
  variables:
    n_ranks: '{processes_per_node}*{n_nodes}'
    batch_submit: '{execute_experiment}'
    mpi_command: mpirun -n {n_ranks}
    platform: [platform1, platform2]
    processes_per_node: [16, 18]
    mpi_name: [intel-mpi, openmpi]
  zips:
    platform_config:
    - platform
    - processes_per_node
  applications:
    wrf@4.2:
      workloads:
        CONUS_12km:
          experiments:
            scaling_{n_nodes}_{platform}:
              variables:
                n_nodes: [1, 2]
              matrix:
              - platform_config
              - n_nodes
  software:
    packages:
      gcc14:
        pkg_spec: gcc@14.2.0
      intel-mpi:
        pkg_spec: intel-oneapi-mpi@2021.17.2
        compiler: gcc14
      openmpi:
        pkg_spec: openmpi@5.0.8 +orterunprefix
      wrfv4-{application::wrf::version}:
        pkg_spec: wrf@{application::wrf::version} build_type=dm+sm compile_type=em_real
          nesting=basic ~pnetcdf
        compiler: gcc14
    environments:
      wrf@4.2-{mpi_name}:
        packages:
        - '{mpi_name}'
        - wrfv4-{application::wrf::version}
