ramble:
  env_vars:
    set:
      OMP_NUM_THREADS: '{n_threads}'
  variables:
    processes_per_node: 16
    mpi_command: 'mpirun -n {n_ranks} -ppn {processes_per_node}'
    batch_submit: '{execute_experiment}'
  applications:
    gromacs: # Application name
      workloads:
        '{app_workloads}': # Workload name from application
          experiments:
            '{type}_{n_ranks}ranks': # Arbitrary experiment name
              variables:
                app_workloads: ['water_gmx50', 'water_bare']
                n_ranks: [1, 2]
                n_threads: '1'
                size: '0003'
                type: ['pme', 'rf']
              matrix:
              - app_workloads
              - type
              - n_ranks
  software:
    packages:
      gcc9:
        pkg_spec: gcc@9.4.0 target=x86_64
        compiler_spec: gcc@9.4.0
      impi2021:
        pkg_spec: intel-oneapi-mpi@2021.11.0 target=x86_64
        compiler: gcc9
      gromacs:
        pkg_spec: gromacs@2021.6
        compiler: gcc9
    environments:
      gromacs:
        packages:
        - gromacs
        - impi2021
