#!/bin/sh
# Copyright 2013-2021 Lawrence Livermore National Security, LLC,
# Google LLC, and other Spack and Ramble Project Developers. See the
# top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)


./share/ramble/qa/run-unit-tests &> /dev/null

if [ $? != 0 ]; then
    echo "Unit tests failed."
    echo "Please run $ramble_root/share/ramble/qa/run-unit-tests"
    echo "And ensure tests are passing before committing"
    exit 1
fi

./share/ramble/qa/run-style-tests &> /dev/null

if [ $? != 0 ]; then
    echo "style tests failed."
    echo "Please run $ramble_root/share/ramble/qa/run-style-tests"
    echo "And ensure tests are passing before committing"
    exit 1
fi

exit 0
