# Copyright 2022-2024 The Ramble Authors
#
# Licensed under the Apache License, Version 2.0 <LICENSE-APACHE or
# https://www.apache.org/licenses/LICENSE-2.0> or the MIT license
# <LICENSE-MIT or https://opensource.org/licenses/MIT>, at your
# option. This file may not be copied, modified, or distributed
# except according to those terms.


steps:
  - name: gcr.io/cloud-builders/git
    args:
      - fetch
      - '--unshallow'
    id: ramble-clone
  - name: us-central1-docker.pkg.dev/$PROJECT_ID/ramble-repo/ramble-${_BASE_IMG}-${_BASE_VER}-spack${_SPACK_REF}-python${_PYTHON_VER}:latest
    args:
      - '-c'
      - |
        cd /workspace

        . /opt/spack/share/spack/setup-env.sh

        spack load py-pip ^python

        pip install -r /workspace/requirements-dev.txt

        export SPACK_PYTHON=`which python3`

        . /workspace/share/ramble/setup-env.sh

        echo "Spack version is $(spack --version)"
        echo "Python version is $(python3 --version)"

        spack mirror add ci_cache ${_CI_CACHE}
        spack buildcache keys --install --trust

        set -e

        ramble workspace create basic_gromacs -c /workspace/examples/basic_gromacs_config.yaml

        ramble workspace activate basic_gromacs

        ramble workspace info

        ramble workspace info --expansions

        ramble info gromacs

        ramble workspace setup --dry-run

        ramble workspace deactivate
    id: ramble-tutorial-test
    entrypoint: /bin/bash
substitutions:
  _SPACK_REF: v0.21.2
  _PYTHON_VER: 3.11.6
  _BASE_IMG: centos
  _BASE_VER: '7'
  _CI_CACHE: gs://spack/latest
timeout: 1500s
options:
  machineType: N1_HIGHCPU_8
