# Copyright 2022-2024 The Ramble Authors
#
# Licensed under the Apache License, Version 2.0 <LICENSE-APACHE or
# https://www.apache.org/licenses/LICENSE-2.0> or the MIT license
# <LICENSE-MIT or https://opensource.org/licenses/MIT>, at your
# option. This file may not be copied, modified, or distributed
# except according to those terms.


steps:
  - name: gcr.io/cloud-builders/git
    args:
      - fetch
      - '--unshallow'
    id: ramble-clone
  - name: us-central1-docker.pkg.dev/$PROJECT_ID/ramble-repo/ramble-${_BASE_IMG}-${_BASE_VER}-spack${_SPACK_REF}-python${_PYTHON_VER}:latest
    args:
      - '-c'
      - |
        cd /workspace

        export PATH=$$(. /opt/spack/share/spack/setup-env.sh && spack location -i miniconda3)/bin:$${PATH}

        . /opt/spack/share/spack/setup-env.sh
        . /workspace/share/ramble/setup-env.sh

        echo "Spack version is $(spack --version)"
        echo "Python version is $(python3 --version)"

        spack mirror add ci_cache ${_CI_CACHE}
        spack buildcache keys --install --trust

        set -e

        ramble workspace create -d zips_and_matrices_wrf -c /workspace/examples/wrf_scaling_config.yaml

        ramble workspace activate ./zips_and_matrices_wrf

        ramble workspace info

        set +e

        cp /workspace/examples/tutorial_7_base_config.yaml zips_and_matrices_wrf/configs/ramble.yaml

        # Expected to give an error
        ramble workspace info


        cp /workspace/examples/tutorial_7_matrix_config.yaml zips_and_matrices_wrf/configs/ramble.yaml

        # Expected to give an error
        ramble workspace info

        set -e


        cp /workspace/examples/tutorial_7_final_config.yaml zips_and_matrices_wrf/configs/ramble.yaml

        ramble workspace info

        ramble workspace setup

        ramble workspace setup --where '{n_ranks} >= 20'

        # Skip execution / analysis because cloud-build machines don't have the right number of cores.

        ramble workspace deactivate
    id: ramble-tutorial-test
    entrypoint: /bin/bash
substitutions:
  _SPACK_REF: v0.21.2
  _PYTHON_VER: 3.11.6
  _BASE_IMG: centos
  _BASE_VER: '7'
  _CI_CACHE: gs://spack/latest
timeout: 1500s
options:
  machineType: N1_HIGHCPU_8
