# -------------------------------------------------------------------------
# This is the default ramble repository configuration. It includes the
# builtin ramble base application repository.
#
# Users can override these settings by editing the following files.
#
# Per-ramble-instance settings (overrides defaults):
#   $RAMBLE_ROOT/etc/ramble/base_application_repos.yaml
#
# Per-user settings (overrides default and site settings):
#   ~/.ramble/base_application_repos.yaml
# -------------------------------------------------------------------------
base_application_repos:
  - $ramble/var/ramble/repos/builtin
