# Gemini review only automatically triggers upon PR open.
# This workflow triggers reviews for subsequent PR updates.
name: Trigger Gemini Review

on:
  pull_request_target:
    types: [synchronize]

jobs:
  post-comment:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      # This is needed as it invokes the issue API to create a comment.
      issues: write
    steps:
      - name: Post trigger comment
        uses: actions/github-script@v9
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '/gemini review'
            })
