name: ramble spelling

on:
  pull_request: []
  push:
    branches-ignore:
    - main
    - gh-pages

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Check Spelling
      uses: crate-ci/typos@v1.20.4
      with:
        files: ./lib/ramble/ramble ./lib/ramble/docs ./examples ./share ./bin ./etc ./var ./README.md
        config: ./.typos.toml
