name: Sphinx build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build docs
      run: |
          pip install -r ./lib/ramble/docs/requirements.txt
          sphinx-build -b html ./lib/ramble/docs ./docs
      #uses: ammaraskar/sphinx-action@0.3
      #with:
      #docs-folder: "./lib/ramble/docs/"
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: html-docs
        path: ./docs/
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/develop'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: "docs"
